### ISSUE TITLE
Finding offsets of event Candies

### ISSUE THREAD

**Issue by DyonisX** [tsuneko/Orange-Juice#1]
I just wanted to thank you for making this and I had no idea where else I could say it, I'm amazed that this is even possible, I tried doing it using cheat engine but because I had 0 candies, no way to make them, and no way to spend them I wasn't able to modify the value in any way, is it possible for me to learn to do it this way?

**Comment by tsuneko** [comment]
Actually I had the same problem where I had no Halloween Candies, but I had Christmas Candies and Oranges and I noticed that their offsets were close to each other (and Stars wasn't), which made sense since Candies seem to be stored on all three profile slots while Stars are stored individually on all three. Anyway, I found the offset by checking for static pointers with a value of 0 around where Christmas Candies were stored. Cheat engine is quite handy and marks these such pointers in green text.
