### ISSUE TITLE
New "Pig hearts" currency added to the game (and hex address)

### ISSUE THREAD

**Issue by hellotinh03** [tsuneko/Orange-Juice#12]
The Pigformation Rerun update added "pig hearts" to the game.

I followed this tutorial on YouTube [https://www.youtube.com/watch?v=hfWOAFsYnFA] to find the address and the offset and it was "0173D3DC" with the offset of "38" pointing to "0173D414".
I don't know what that means or what to do next since I have barely any coding experience but I hope this helps.

**Comment by tsuneko** [comment]
Yup, so that's a static address. 999orange uses signatures rather than static offsets as those can become outdated very quickly. Anyway, for future's sake, I've added additional parsing for static offsets in the latest release.

The reason we can't use 0173D414 by itself is because this value can change depending on the user's system. So we want to find the offset of this address when compared to the base address given by the orange juice process.

To do this in Cheat Engine, you double click on the address (0173D414) to find the offset from the base process (100orange.exe+69D414), which would let you find the offset: 69D414. This value is added to conf.ini, under the new [static offsets] section.

Anyway, thank you for your help, I've already added the pig hearts to the configuration file in the lastest release, you will just need to remove the ; at the beginning of the line.
